name: JSR Publish

on:
  push:
    branches:
      - develop-deno-i2p-sam

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: develop-deno-i2p-sam
      - run: npx jsr publish
